spring:
  profiles:
    active:
     -dev
---
server:
  port: 8012
spring:
  application:
    name: PRODUCT-PROVIDER
  profiles: dev #开发环境
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: 6280976
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8013
spring:
  application:
    name: PRODUCT-PROVIDER-TEST
  profiles: test #开发环境
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou-test
    username: root
    password: 6280976
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
