spring:
  profiles:
    active:
     -dev
---
server:
  port: 8001
spring:
  application:
    name: PLAT-SERVER-DEV
  profiles: dev #开发环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8002
spring:
  application:
    name: PLAT-SERVER-TEST
  profiles: test #测试环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka