spring:
  profiles:
    active: -dev
---
server:
  port: 9527
spring:
  application:
    name: aigou-config-server-dev
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527 #显示的名字而已
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: plat-server-dev
    plat.path: /plat/**
  ignored-services: "*"
  prefix: "/aigou"
---
server:
  port: 9528
spring:
  application:
    name: aigou-config-server-test
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9528 #显示的名字而已
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: plat-server-test
    plat.path: /plat/**
  ignored-services: "*"
  prefix: "/aigou"
